name: mobile_app_inventory_qr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  fl_chart: ^0.64.0
  intl: 0.19.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  image_picker: ^1.0.5
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  open_file: ^3.5.10
  url_launcher: ^6.3.1
  webview_flutter: ^4.7.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  change_app_package_name: ^1.1.20

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/

# Evitar errores en macOS por open_file
platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos:

