name: mobile_app_inventory_qr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.2
  pdf: ^3.10.7
  printing: ^5.11.1
  fl_chart: ^0.64.0
  intl: ^0.19.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  image_picker: ^1.0.5
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5

  # Firebase (versiones compatibles entre sí)
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.3
  firebase_auth: ^4.17.4

  # Abrir archivos con open_file
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  change_app_package_name: ^1.1.20

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/

# Evitar errores en macOS por open_file
platforms:
  macos:
    plugin:
      implements: none
=======
  pie_chart: ^5.1.0
  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8

  # Utilidades
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

  # PDF y gráficos
  pdf: ^3.10.4
  printing: ^5.12.0
  fl_chart: ^0.64.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
>>>>>>> f084ef998e4084b27316a359a953092a6212c3fc
